### ISSUE TITLE
Interact hud appears on round over cinematic when is closer to gun

### ISSUE THREAD

**Issue by GLideKS** [Saxashitter/murder-mystery#19]
![srb20224](https://github.com/user-attachments/assets/5c4c8cb8-e369-414b-bb24-8bab2e9782c4)

**Comment by Jiskster** [comment]
Fixed in commit: https://github.com/Saxashitter/murder-mystery/commit/c7ce79dfe2bf7211f60612192f7acd6182fd48fd
