### ISSUE TITLE
Remove require system when SRB2 2.2.14 releases (MM.require)

### ISSUE THREAD

**Issue by Jiskster** [Saxashitter/murder-mystery#2]
Instead, use the new `loadfile` function.
https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1615

Doing this will prevent using `dofile` in independent files that aren't related to game/weapon initiating.

**Comment by Saxashitter** [comment]
just checked it out, shouldnt be any of my concern

this seems to be useful for a possible weapon system refactor, but i dont think ill be needing to do ``loadfile("Libs/shallowCopy")()``

**Comment by Jiskster** [comment]
Reopened because you misunderstood it

**Comment by Saxashitter** [comment]
i dont get it

i used smth like this in love2d
